apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-crud-server-pvc
  labels:
    app: mongo-crud-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi